### ISSUE TITLE
How to make it work!

### ISSUE THREAD

**Issue by adrianvintu** [bhagat-techind/flutter_sharing_intent#52]
Since the original developer does not answer anymore, please use the following steps to make it work:

1. use the installation steps from here

2. do not use 
`flutter_sharing_intent: ^1.1.0`

instead use

```
flutter_sharing_intent:
  git: https://github.com/FelixGaebler/flutter_sharing_intent.git
```

Source: https://github.com/bhagat-techind/flutter_sharing_intent/issues/29#issuecomment-1741734830

3. change the build order like here https://github.com/bhagat-techind/flutter_sharing_intent/issues/36#issuecomment-1826251215 which redirects to https://github.com/flutter/flutter/issues/135739#issuecomment-1741814813

**Comment by Hithori** [comment]
Package is working, but 1.1.0 isn't last version.
I use:
```
  flutter_sharing_intent:
    git:
      url: https://github.com/bhagat-techind/flutter_sharing_intent
      ref: 9c42247b85b42ba93e19d57558cb22d7ac2cbaab // last known commit 
``` 
and everything works
